configure: add --enable-gfio
Signed-off-by: Jens Axboe <axboe@kernel.dk>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -102,12 +102,19 @@ cpu=""
 
 cc="${CC-${cross_prefix}gcc}"
 
+# default options
+gfio="no"
+
 # parse options
 for opt do
   optarg=`expr "x$opt" : 'x[^=]*=\(.*\)'`
   case "$opt" in
-  --cc=*) CC="$optarg"
-  ;;
+  --cc=*)
+    CC="$optarg"
+    ;;
+  --enable-gfio)
+    gfio="yes"
+    ;;
   *)
   echo "Bad option $opt"
   exit 1
@@ -789,6 +796,43 @@ if compile_prog "" "" "__thread"; then
 fi
 echo "__thread                      $tls_thread"
 
+##########################################
+# Whether or not __thread is supported for TLS
+if test "$gfio" = "yes" ; then
+  cat > $TMPC << EOF
+#include <glib.h>
+#include <cairo.h>
+#include <gtk/gtk.h>
+int main(void)
+{
+  gdk_threads_enter();
+  gtk_main();
+  gdk_threads_leave();
+  return 0;
+}
+EOF
+GTK_CFLAGS=$(pkg-config --cflags gtk+-2.0 gthread-2.0)
+if test "$?" != "0" ; then
+  echo "configure: gtk and gthread not found"
+  exit 1
+fi
+GTK_LIBS=$(pkg-config --libs gtk+-2.0 gthread-2.0)
+if test "$?" != "0" ; then
+  echo "configure: gtk and gthread not found"
+  exit 1
+fi
+if compile_prog "$GTK_CFLAGS" "$GTK_LIBS" "gfio"; then
+  gfio="yes"
+  LIBS="$LIBS $GTK_LIBS"
+  CFLAGS="$CFLAGS $GTK_CFLAGS"
+else
+  echo "Please install gtk and gdk libraries"
+  gfio="no"
+fi
+fi
+
+echo "gfio                          $gfio"
+
 #############################################################################
 
 echo "# Automatically generated by configure - do not modify" > $config_host_mak
@@ -889,6 +933,10 @@ fi
 if test "$tls_thread" = "yes" ; then
   echo "CONFIG_TLS_THREAD=y" >> $config_host_mak
 fi
+if test "$gfio" = "yes" ; then
+  echo "CONFIG_GFIO=y" >> $config_host_mak
+fi
 
 echo "LIBS+=$LIBS" >> $config_host_mak
+echo "CFLAGS+=$CFLAGS" >> $config_host_mak
 echo "CC=$cc" >> $config_host_mak
